### ISSUE TITLE
need ~10 hrs to run one epoch

### ISSUE THREAD

**Issue by Deanplayerljx** [rowanz/r2c#11]
Hi,

Thanks for your great work! I tried to run your train script in the "models" folder, and it showed it will approximately take about 10 hrs to train one epoch. After I used the line_profile tool to check the running time analysis of the train script, I found that this line of code takes 90% of the total running time:
`for b, (time_per_batch, batch) in enumerate(time_batch(train_loader if args.no_tqdm else tqdm(train_loader), reset_every=ARGS_RESET_EVERY)):`

I think this line basically calls the collate_fn() in the DataLoader object and the __get_item__() in the Dataset object. Do you have any ideas that why it takes so long to run one epoch?

I'm using 4 CPUs with 20GB memory in total and Telsla V100 on a Google Cloud VM instance.

PS: I also tried to replace all the executions inside that loop with "pass", 
`for b, (time_per_batch, batch) in enumerate(time_batch(train_loader if args.no_tqdm else tqdm(train_loader), reset_every=ARGS_RESET_EVERY)):   pass`
and it still needed the same amount of time for one epoch.

**Comment by Zzmonica** [comment]
Have you accelerate your run time? And how? Thanks!
