### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AmingWu** [rowanz/r2c#13]
When I run your code, there is an error 'no module named 'torchvision.layers'. and I can not use the link 

pip install git+git://github.com/pytorch/vision.git@24577864e92b72f7066e1ed16e978e873e19d13d.

**Comment by flyingmanPan** [comment]
The module is in that torchvision, so that package MUST be installed.
Maybe you should uninstall the old torchvision, and configure CUDA_HOME, then install that package.

**Comment by jaeyun95** [comment]
1) sudo apt-get install git-core 
and 
2) pip install git+git://github.com/pytorch/vision.git@24577864e92b72f7066e1ed16e978e873e19d13d
try it! 
i had a same problem and solve it!

**Comment by rowanz** [comment]
thanks for the help @jaeyun95 !! closed 😄

**Comment by AmingWu** [comment]
@rowanz when I run sudo apt-get install git-core and pip install git+git://github.com/pytorch/vision.git@24577864e92b72f7066e1ed16e978e873e19d13d, it also does not work.

**Comment by venkata-srinivasan** [comment]
I am also facing the same issue. The above fix doesn't work

**Comment by KanswerG** [comment]
i cannot download git, what should i do
