### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/disk4/libuwei/r2c-master/data/vcr1images/movieclips_S.W.A.T./aDU5CcINqyI@29.jpg'

### ISSUE THREAD

**Issue by Anter001** [rowanz/r2c#20]
Hi Rowan,

When I run :
python train.py -params multiatt/default.json -folder saves/flagship_answer 

There is an error:
**FileNotFoundError: [Errno 2] No such file or directory: '/disk4/libuwei/r2c-master/data/vcr1images/movieclips_S.W.A.T./aDU5CcINqyI@29.jpg'**

environment information:
PyTorch version: 1.0.1.post2
CUDA used to build PyTorch: 8.0.44
OS：centos 7.3
GCC version: 5.5
Python version: 3.6
Is CUDA available: yes
GPU: Tesla K20c
Nvidia driver version: 375.66

**Comment by 2name** [comment]
But I can find it  
/disk4/libuwei/r2c-master/data/vcr1images/movieclips_S.W.A.T./aDU5CcINqyI@29.jpg

**Comment by Anter001** [comment]
@rowanz 
But I can find it
/disk4/libuwei/r2c-master/data/vcr1images/movieclips_S.W.A.T./aDU5CcINqyI@29.jpg

**Comment by Anter001** [comment]
Hi,rowanz.
I solved it.

**Comment by rowanz** [comment]
awesome! I'm closing this now. could you give me more info about what the problem was / how you fixed it?
