### ISSUE TITLE
Why not read h5 file in VCR __init__ function

### ISSUE THREAD

**Issue by yuweihao** [rowanz/r2c#25]
https://github.com/rowanz/r2c/blob/71ee6841b64a58c502f9ac85d72e73761adb14db/dataloaders/vcr.py#L229-L231

Hi @rowanz , thanks for your sharing your nice code again!
I am confused about this and want to know the reason why not read h5 file in __init__ but in __getitem__.

Thank you very much!

**Comment by rowanz** [comment]
it's because h5 arrays aren't thread safe, so it gives problems when you use multiple processors for dataloading :)

**Comment by yuweihao** [comment]
wow, thanks for your reply! I learned it, thank you (^_^)
