### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AmingWu** [rowanz/r2c#26]
When I run your code, there is an error 'no module named 'torchvision.layers'. and I can not use the link

pip install git+git://github.com/pytorch/vision.git@24577864e92b72f7066e1ed16e978e873e19d13d.

When I run sudo apt-install git-core and pip install git+git://github.com/pytorch/vision.git@24577864e92b72f7066e1ed16e978e873e19d13d, it also does not work.

**Comment by AmingWu** [comment]
Thank you very much. I have solved this problem. The above method is work.

**Comment by venkata-srinivasan** [comment]
Can you share how this error was resolved?
