### ISSUE TITLE
two links in data/README.md don't work

### ISSUE THREAD

**Issue by yuweihao** [rowanz/r2c#3]
Hi @rowanz ,
    Thanks for your wonderful work and code.
    I found the two following links don't work and the bert representations couldn't be downloaded from them.
https://s3-us-west-2.amazonaws.com/ai2-rowanz/r2c/bert_da_answer_test.h5
https://s3-us-west-2.amazonaws.com/ai2-rowanz/r2c/bert_da_rationale_test.h5

**Comment by yuweihao** [comment]
I found the two links could work again.

**Comment by rowanz** [comment]
hey Weihao,

sorry for the lack of response on my part!! I just fixed the link last night 😄

the only thing I should mention is that the test answer/rationale embeddings are only going to be useful for submitting predictions to the (future) leaderboard. In the short term, it's probably best to just evaluate models on the evaluation set. working on getting the leaderboard set up as soon as possible!

**Comment by yuweihao** [comment]
Hi Rowan, 

Thanks for your response (^_^)
