### ISSUE TITLE
Import error : undefined symbol issue

### ISSUE THREAD

**Issue by woosikyang** [rowanz/r2c#31]
![Screenshot from 2019-10-24 10-20-22](https://user-images.githubusercontent.com/44371956/67445473-04326300-f648-11e9-96e0-34ae5e00b1e8.png)

I've followed the process from creating a new conda environment but 
I can not get the leaderboard output, I get the import issue about cuda

Do you have any idea?

**Comment by Hastyrush** [comment]
Most probably one of the following:

1. Your cuda is not compiled properly
2. Your cuda version does not support the Pytorch version used
3. Gcc version used to compile the library files are not compatible (look up gcc compatibility with 
    cuda version)

**Comment by woosikyang** [comment]
yeah I re-installed following the directions. Problem solved Thanks :)
