### ISSUE TITLE
How can I download vcr v1.0 data?

### ISSUE THREAD

**Issue by tuyunbin** [rowanz/r2c#34]
Hi, rowanz, thanks for your great work. But I have a problem that I cannot find the link to download VCR data, i.e. images and annotations. I click 'Annotations' and 'Images', but it dosen't have any response.
![image](https://user-images.githubusercontent.com/22414019/80953247-b6d05300-8e2d-11ea-9481-efb2903b4020.png)

**Comment by tuyunbin** [comment]
Hi, rowanz, I found this page has been changed and I can download these two files. Thank you!

**Comment by 489597448** [comment]
where is the download link
