### ISSUE TITLE
segmentation fault error

### ISSUE THREAD

**Issue by yangshao** [rowanz/r2c#4]
I try to run the train.py, but the code fails on the line:  
model = Model.from_params(vocab=train.vocab, params=params['model'])
The error infomation is: 
01/10/2019 21:36:36 - INFO - allennlp.common.params -   model.initializer = [['.*final_mlp.*weight', {'type': 'xavier_uniform'}], ['.*final_mlp.*bias', {'type': 'zero'}], ['.*weight_ih.*', {'type': 'xavier_uniform'}], ['.*weight_hh.*', {'type': 'orthogonal'}], ['.*bias_ih.*', {'type': 'zero'}], ['.*bias_hh.*', {'type': 'lstm_hidden_bias'}]]
01/10/2019 21:36:36 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'type': 'xavier_uniform'} and extras {}
01/10/2019 21:36:36 - INFO - allennlp.common.params -   model.initializer.list.list.type = xavier_uniform
01/10/2019 21:36:36 - INFO - allennlp.common.params -   Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
01/10/2019 21:36:36 - INFO - allennlp.common.params -   CURRENTLY DEFINED PARAMETERS:
01/10/2019 21:36:36 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'type': 'zero'} and extras {}
01/10/2019 21:36:36 - INFO - allennlp.common.params -   model.initializer.list.list.type = zero
01/10/2019 21:36:36 - INFO - allennlp.common.params -   Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
01/10/2019 21:36:36 - INFO - allennlp.common.params -   CURRENTLY DEFINED PARAMETERS:
01/10/2019 21:36:36 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'type': 'xavier_uniform'} and extras {}
01/10/2019 21:36:36 - INFO - allennlp.common.params -   model.initializer.list.list.type = xavier_uniform
01/10/2019 21:36:36 - INFO - allennlp.common.params -   Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
01/10/2019 21:36:36 - INFO - allennlp.common.params -   CURRENTLY DEFINED PARAMETERS:
01/10/2019 21:36:36 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'type': 'orthogonal'} and extras {}
01/10/2019 21:36:36 - INFO - allennlp.common.params -   model.initializer.list.list.type = orthogonal
01/10/2019 21:36:36 - INFO - allennlp.common.params -   Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
01/10/2019 21:36:36 - INFO - allennlp.common.params -   CURRENTLY DEFINED PARAMETERS:
01/10/2019 21:36:36 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'type': 'zero'} and extras {}
01/10/2019 21:36:36 - INFO - allennlp.common.params -   model.initializer.list.list.type = zero
01/10/2019 21:36:36 - INFO - allennlp.common.params -   Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
01/10/2019 21:36:36 - INFO - allennlp.common.params -   CURRENTLY DEFINED PARAMETERS:
01/10/2019 21:36:36 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'type': 'lstm_hidden_bias'} and extras {}
01/10/2019 21:36:36 - INFO - allennlp.common.params -   model.initializer.list.list.type = lstm_hidden_bias
01/10/2019 21:36:36 - INFO - allennlp.common.params -   Converting Params object to dict; logging of default values will not occur when dictionary parameters are used subsequently.
01/10/2019 21:36:36 - INFO - allennlp.common.params -   CURRENTLY DEFINED PARAMETERS:
01/10/2019 21:36:37 - INFO - allennlp.nn.initializers -   Initializing parameters
01/10/2019 21:36:37 - INFO - allennlp.nn.initializers -   Initializing span_encoder._module._module.weight_ih_l0 using .*weight_ih.* intitializer
01/10/2019 21:36:37 - INFO - allennlp.nn.initializers -   Initializing span_encoder._module._module.weight_hh_l0 using .*weight_hh.* intitializer
Segmentation fault

**Comment by yangshao** [comment]
after reinstalling the anaconda, the problem is fixed.

**Comment by Anter001** [comment]
> after reinstalling the anaconda, the problem is fixed.

when I run this code, there is an error 'Segmentation fault (core dumped)'.have you solved it? thank you for your reply！

**Comment by Zzmonica** [comment]
> > after reinstalling the anaconda, the problem is fixed.
> 
> when I run this code, there is an error 'Segmentation fault (core dumped)'.have you solved it? thank you for your reply！

Hi, have you solve this problem? I run into the same one, and don't know how to do. Looking forward to your reply!

**Comment by yeezhu** [comment]
The "segment fault error" occurs when I step into the forward function of the ROIAlign layer. Maybe it is about the version of some python dependencies. 
@rowanz, could you please provide the environment.yml file of your r2c conda env?

**Comment by rowanz** [comment]
can you double check that you've installed torchvision from the layers branch?

```
pip install git+git://github.com/pytorch/vision.git@24577864e92b72f7066e1ed16e978e873e19d13d
```

**Comment by yeezhu** [comment]
@rowanz 
Thanks for your quick reply!
I reinstalled the torchvision and test the ROIAlign layer, the error is still there. 
Maybe it is about the version of the other dependency packages, such as numpy, six, or pillow?
![image](https://user-images.githubusercontent.com/30250590/63313110-fc97ca80-c335-11e9-8714-370b9fb1e687.png)

**Comment by yeezhu** [comment]
I changed the linux kernel and the problem is fixed.
Thank you very much!

**Comment by tanjatang** [comment]
Hi, I have the same problem , how did you solve it? just reinstall anaconda?

**Comment by tanjatang** [comment]
finally I solved the problem by reinstalling anaconda and update cuda9 to cuda10
