### ISSUE TITLE
meaning of ctx_answer

### ISSUE THREAD

**Issue by yangshao** [rowanz/r2c#5]
I'm looking at the bert representation of the question, it seems that ctx_answer0, ctx_answer1, ctx_answer2, ctx_answer3 should be the same representation for the question for each sample. But in the downloaded bert data, they are not. why does this happen?

**Comment by abhinavkaul95** [comment]
Hi @yangshao, can you please explain this a little bit if you have understood it? I am facing the same issue to understand why ctx_answer* embeddings are different from one another.
