### ISSUE TITLE
Question about adversarial Matching

### ISSUE THREAD

**Issue by yangshao** [rowanz/r2c#8]
In the paper, it's said that "each answer appears exactly four times in  the dataset".  I try to verify this. But I cannot get this conclusion for the train.jsonl and val.jsonl file. Can you explain more about this?  Besides, does this mean all correct answers appears 4 times, or all answers candidates appears  4 times?  Thanks.

**Comment by rowanz** [comment]
answered here https://groups.google.com/forum/#!topic/visualcommonsense/-oIn2QLK1uA :)
